export const ON_SEARCH_CHANGE = "ON_SEARCH_CHANGE";


export const ON_ROBOTS_PENDING = "ON_ROBOTS_PENDING";
export const ON_ROBOTS_SUCCESS = "ON_ROBOTS_SUCCESS";
export const ON_ROBOTS_FAILED = "ON_ROBOTS_FAILED";
